export const CHECK_LOGIN_STATE_LOGGED_IN = 'CHECK_LOGIN_STATE_LOGGED_IN';
export const CHECK_LOGIN_STATE_NOT_LOGGED_IN = 'CHECK_LOGIN_STATE_NOT_LOGGED_IN';

export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

export const GET_ME_DATA = 'GET_ME_DATA';
export const GET_ME_DATA_SUCCESS = 'GET_ME_DATA_SUCCESS';
export const GET_ME_DATA_FAIL = 'GET_ME_DATA_FAIL';

export const BIND_WALLET_ADDRESS = 'BIND_WALLET_ADDRESS';

export const GET_FOLLOW_CONFIG_REQUEST = 'GET_FOLLOW_CONFIG_REQUEST';
export const GET_FOLLOW_CONFIG_REQUEST_SUCCESS = 'GET_FOLLOW_CONFIG_REQUEST_SUCCESS';
export const GET_FOLLOW_CONFIG_REQUEST_FAIL = 'GET_FOLLOW_CONFIG_REQUEST_FAIL';

export const CHECK_AGREEMENT = 'CHECK_AGREEMENT';

export const SHOW_FOLLOW_CONFIG_MODAL = 'SHOW_FOLLOW_CONFIG_MODAL';
export const UPDATE_FOLLOW_CONFIG = 'UPDATE_FOLLOW_CONFIG';
export const SEND_FOLLOW_CONFIG_REQUEST = 'SEND_FOLLOW_CONFIG_REQUEST';
export const SEND_FOLLOW_CONFIG_REQUEST_SUCCESS = 'SEND_FOLLOW_CONFIG_REQUEST_SUCCESS';
export const SEND_FOLLOW_CONFIG_REQUEST_FAIL = 'SEND_FOLLOW_CONFIG_REQUEST_FAIL';

export const SEND_CANCLE_COPY_REQUEST = 'SEND_CANCLE_COPY_REQUEST';
export const SEND_CANCLE_COPY_REQUEST_SUCCESS = 'SEND_CANCLE_COPY_REQUEST_SUCCESS';
export const SEND_CANCLE_COPY_REQUEST_FAIL = 'SEND_CANCLE_COPY_REQUEST_FAIL';

export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';