export const CHECK_LOGIN_STATE_LOGGED_IN = 'CHECK_LOGIN_STATE_LOGGED_IN';
export const CHECK_LOGIN_STATE_NOT_LOGGED_IN = 'CHECK_LOGIN_STATE_NOT_LOGGED_IN';

export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

export const GET_ME_DATA = 'GET_ME_DATA';
export const GET_ME_DATA_SUCCESS = 'GET_ME_DATA_SUCCESS';
export const GET_ME_DATA_FAIL = 'GET_ME_DATA_FAIL';

export const BIND_WALLET_ADDRESS = 'BIND_WALLET_ADDRESS';
export const SET_NICKNAME = 'SET_NICKNAME';
export const UPDATE_MAX_NICKNAME_LENGTH = 'UPDATE_MAX_NICKNAME_LENGTH';
export const SET_NICKNAME_SUCCESS = 'SET_NICKNAME_SUCCESS';
export const SET_NICKNAME_FAIL = 'SET_NICKNAME_FAIL';
export const SET_PORTRAIT = 'SET_PORTRAIT';
export const UPLOAD_PORTRAIT_SUCCESS = 'UPLOAD_PORTRAIT_SUCCESS';
export const UPLOAD_PORTRAIT_FAILURE = 'UPLOAD_PORTRAIT_FAILURE';

export const GET_FOLLOW_CONFIG_REQUEST = 'GET_FOLLOW_CONFIG_REQUEST';
export const GET_FOLLOW_CONFIG_REQUEST_SUCCESS = 'GET_FOLLOW_CONFIG_REQUEST_SUCCESS';
export const GET_FOLLOW_CONFIG_REQUEST_FAIL = 'GET_FOLLOW_CONFIG_REQUEST_FAIL';

export const CHECK_AGREEMENT = 'CHECK_AGREEMENT';

export const SHOW_FOLLOW_CONFIG_MODAL = 'SHOW_FOLLOW_CONFIG_MODAL';
export const UPDATE_FOLLOW_CONFIG = 'UPDATE_FOLLOW_CONFIG';
export const SEND_FOLLOW_CONFIG_REQUEST = 'SEND_FOLLOW_CONFIG_REQUEST';
export const SEND_FOLLOW_CONFIG_REQUEST_SUCCESS = 'SEND_FOLLOW_CONFIG_REQUEST_SUCCESS';
export const SEND_FOLLOW_CONFIG_REQUEST_FAIL = 'SEND_FOLLOW_CONFIG_REQUEST_FAIL';

export const SEND_CANCLE_COPY_REQUEST = 'SEND_CANCLE_COPY_REQUEST';
export const SEND_CANCLE_COPY_REQUEST_SUCCESS = 'SEND_CANCLE_COPY_REQUEST_SUCCESS';
export const SEND_CANCLE_COPY_REQUEST_FAIL = 'SEND_CANCLE_COPY_REQUEST_FAIL';

export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';

export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST';
export const GET_MESSAGE_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS';
export const GET_MESSAGE_LIST_ATTACH = 'GET_MESSAGE_LIST_ATTACH';
export const GET_MESSAGE_LIST_ATTACH_SUCCESS = 'GET_MESSAGE_LIST_ATTACH_SUCCESS';
export const GET_MESSAGE_LIST_FAIL = 'GET_MESSAGE_LIST_FAIL';
export const SET_MESSAGE_READ = 'SET_MESSAGE_READ';
export const UPDATE_UNREAD = 'UPDATE_UNREAD';
export const GET_VERSION = 'GET_VERSION';
export const SET_LOACL_NICKNAME = 'SET_LOACL_NICKNAME';
export const SET_LOACL_NICKNAME_SUCCESS = 'SET_LOACL_NICKNAME_SUCCESS';
export const SET_LOACL_NICKNAME_FAIL = 'SET_LOACL_NICKNAME_FAIL';
export const GET_TRADE_STYLE_SUCCESS = 'GET_TRADE_STYLE_SUCCESS';
export const GET_TRADE_STYLE_FAIL = 'GET_TRADE_STYLE_FAIL';