//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earn.
        /// </summary>
        internal static string Earn {
            get {
                return ResourceManager.GetString("Earn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lose.
        /// </summary>
        internal static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} you copied is closed at {1}. You {2} {3}..
        /// </summary>
        internal static string MsgType_AutoClose_Follow_Body {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Follow_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Closed.
        /// </summary>
        internal static string MsgType_AutoClose_Follow_Header {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Follow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is closed at {1}. You {2} {3}..
        /// </summary>
        internal static string MsgType_AutoClose_Liquidate_Body {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Liquidate_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Closed.
        /// </summary>
        internal static string MsgType_AutoClose_Liquidate_Header {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Liquidate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is closed by stop price {1}. You {2} {3}..
        /// </summary>
        internal static string MsgType_AutoClose_Stop_Body {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Stop_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Closed.
        /// </summary>
        internal static string MsgType_AutoClose_Stop_Header {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Stop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is closed by profit price {1}. You {2} {3}..
        /// </summary>
        internal static string MsgType_AutoClose_Take_Body {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Take_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Closed.
        /// </summary>
        internal static string MsgType_AutoClose_Take_Header {
            get {
                return ResourceManager.GetString("MsgType_AutoClose_Take_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This nickname is already used..
        /// </summary>
        internal static string NicknameExisted {
            get {
                return ResourceManager.GetString("NicknameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds..
        /// </summary>
        internal static string NotEnoughBalance {
            get {
                return ResourceManager.GetString("NotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security is closed..
        /// </summary>
        internal static string ProductClosed {
            get {
                return ResourceManager.GetString("ProductClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address is already used by another user..
        /// </summary>
        internal static string THTAddressExisted {
            get {
                return ResourceManager.GetString("THTAddressExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Position.
        /// </summary>
        internal static string TransferType_Close {
            get {
                return ResourceManager.GetString("TransferType_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Position.
        /// </summary>
        internal static string TransferType_Open {
            get {
                return ResourceManager.GetString("TransferType_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string TransferType_THTDeposit {
            get {
                return ResourceManager.GetString("TransferType_THTDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        internal static string TransferType_THTWithdrawal {
            get {
                return ResourceManager.GetString("TransferType_THTWithdrawal", resourceCulture);
            }
        }
    }
}
